require('dotenv').config();
const mongoose = require('mongoose');
const User = require('./models/User');
const Block = require('./models/Block');
const Notification = require('./models/Notification');

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB for seeding...');

    // Clear existing data
    await User.deleteMany({});
    await Block.deleteMany({});
    await Notification.deleteMany({});

    // Create users
    const manager = await User.create({
      name: 'Sarah Chen (Manager)',
      email: 'demo-manager@flowsync.ic',
      role: 'manager',
      avatar: '',
      skills: [],
      availability: 'available',
      rating: 5,
      completedBlocks: 0,
    });

    const engineers = await User.insertMany([
      {
        name: 'Alex Rivera',
        email: 'demo-engineer@flowsync.ic',
        role: 'engineer',
        skills: ['Inverter', 'Current Mirror', 'OTA', 'Differential Pair'],
        availability: 'available',
        rating: 4.5,
        completedBlocks: 12,
        totalHoursLogged: 320,
      },
      {
        name: 'Priya Sharma',
        email: 'priya@flowsync.ic',
        role: 'engineer',
        skills: ['Bandgap', 'LDO', 'OTA', 'PLL'],
        availability: 'available',
        rating: 4.8,
        completedBlocks: 18,
        totalHoursLogged: 485,
      },
      {
        name: 'James Wilson',
        email: 'james@flowsync.ic',
        role: 'engineer',
        skills: ['ADC', 'DAC', 'Comparator', 'Current Mirror'],
        availability: 'partially_available',
        rating: 4.2,
        completedBlocks: 8,
        totalHoursLogged: 210,
      },
      {
        name: 'Mei Lin Zhang',
        email: 'mei@flowsync.ic',
        role: 'engineer',
        skills: ['PLL', 'OTA', 'Differential Pair', 'Inverter'],
        availability: 'available',
        rating: 4.7,
        completedBlocks: 15,
        totalHoursLogged: 400,
      },
      {
        name: 'Raj Patel',
        email: 'raj@flowsync.ic',
        role: 'engineer',
        skills: ['Bandgap', 'LDO', 'Current Mirror', 'Comparator'],
        availability: 'busy',
        rating: 3.9,
        completedBlocks: 6,
        totalHoursLogged: 150,
      },
    ]);

    // Create blocks
    const blocks = await Block.insertMany([
      {
        name: 'INV_5T_Core',
        type: 'Inverter',
        description: '5-transistor inverter core cell for digital logic interface',
        estimatedArea: 25.5,
        technologyNode: '28nm',
        complexityLevel: 'Low',
        status: 'Completed',
        baseHours: 8,
        estimatedHours: 12,
        actualHours: 10,
        aiPredictedHours: 11.5,
        delayRisk: 'Low',
        priority: 'Medium',
        assignedTo: engineers[0]._id,
        createdBy: manager._id,
        startDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        completedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
          { status: 'In Progress', changedBy: engineers[0]._id, comment: 'Started layout' },
          { status: 'DRC', changedBy: engineers[0]._id, comment: 'DRC check initiated' },
          { status: 'LVS', changedBy: engineers[0]._id, comment: 'LVS verification' },
          { status: 'Review', changedBy: engineers[0]._id, comment: 'Submitted for review' },
          { status: 'Completed', changedBy: manager._id, comment: 'Approved' },
        ],
        approvals: [{ submittedBy: engineers[0]._id, reviewedBy: manager._id, status: 'approved', comments: 'Excellent work!' }],
      },
      {
        name: 'CM_Cascode_HV',
        type: 'Current Mirror',
        description: 'High-voltage cascode current mirror for bias generation',
        estimatedArea: 48.2,
        technologyNode: '65nm',
        complexityLevel: 'Medium',
        status: 'In Progress',
        baseHours: 12,
        estimatedHours: 19.8,
        actualHours: 8,
        aiPredictedHours: 18.5,
        delayRisk: 'Low',
        priority: 'High',
        assignedTo: engineers[0]._id,
        createdBy: manager._id,
        startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
          { status: 'In Progress', changedBy: engineers[0]._id, comment: 'Layout started' },
        ],
      },
      {
        name: 'DP_NMOS_LowNoise',
        type: 'Differential Pair',
        description: 'Low-noise NMOS differential pair for front-end amplifier',
        estimatedArea: 85.0,
        technologyNode: '45nm',
        complexityLevel: 'High',
        status: 'DRC',
        baseHours: 20,
        estimatedHours: 65,
        actualHours: 42,
        aiPredictedHours: 58,
        delayRisk: 'Medium',
        priority: 'Urgent',
        assignedTo: engineers[1]._id,
        createdBy: manager._id,
        startDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
          { status: 'In Progress', changedBy: engineers[1]._id, comment: 'Started' },
          { status: 'DRC', changedBy: engineers[1]._id, comment: 'Running DRC' },
        ],
      },
      {
        name: 'BG_Precision_V2',
        type: 'Bandgap',
        description: 'Precision bandgap reference with curvature correction',
        estimatedArea: 120.0,
        technologyNode: '28nm',
        complexityLevel: 'Critical',
        status: 'Review',
        baseHours: 32,
        estimatedHours: 192,
        actualHours: 175,
        aiPredictedHours: 180,
        delayRisk: 'High',
        priority: 'Urgent',
        assignedTo: engineers[1]._id,
        createdBy: manager._id,
        startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
          { status: 'In Progress', changedBy: engineers[1]._id, comment: 'Started' },
          { status: 'DRC', changedBy: engineers[1]._id, comment: 'DRC pass' },
          { status: 'LVS', changedBy: engineers[1]._id, comment: 'LVS clean' },
          { status: 'Review', changedBy: engineers[1]._id, comment: 'Ready for review' },
        ],
        approvals: [{ submittedBy: engineers[1]._id, status: 'pending' }],
      },
      {
        name: 'OTA_TwoStage_Comp',
        type: 'OTA',
        description: 'Two-stage OTA with Miller compensation for ADC driver',
        estimatedArea: 200.0,
        technologyNode: '45nm',
        complexityLevel: 'High',
        status: 'LVS',
        baseHours: 40,
        estimatedHours: 130,
        actualHours: 95,
        aiPredictedHours: 120,
        delayRisk: 'Medium',
        priority: 'High',
        assignedTo: engineers[3]._id,
        createdBy: manager._id,
        startDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
          { status: 'In Progress', changedBy: engineers[3]._id, comment: 'Started' },
          { status: 'DRC', changedBy: engineers[3]._id, comment: 'DRC clean' },
          { status: 'LVS', changedBy: engineers[3]._id, comment: 'LVS in progress' },
        ],
      },
      {
        name: 'LDO_200mA_LP',
        type: 'LDO',
        description: 'Low-power 200mA LDO regulator with fast transient response',
        estimatedArea: 150.0,
        technologyNode: '28nm',
        complexityLevel: 'High',
        status: 'Not Started',
        baseHours: 35,
        estimatedHours: 131.25,
        actualHours: 0,
        aiPredictedHours: 125,
        delayRisk: null,
        priority: 'Medium',
        createdBy: manager._id,
        dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
        ],
      },
      {
        name: 'PLL_Fractional_N',
        type: 'PLL',
        description: 'Fractional-N PLL for clock generation with low jitter',
        estimatedArea: 350.0,
        technologyNode: '14nm',
        complexityLevel: 'Critical',
        status: 'In Progress',
        baseHours: 60,
        estimatedHours: 480,
        actualHours: 120,
        aiPredictedHours: 450,
        delayRisk: 'High',
        priority: 'Urgent',
        assignedTo: engineers[3]._id,
        createdBy: manager._id,
        startDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
          { status: 'In Progress', changedBy: engineers[3]._id, comment: 'Layout started' },
        ],
      },
      {
        name: 'SAR_ADC_10bit',
        type: 'ADC',
        description: '10-bit SAR ADC with 100MS/s sampling rate',
        estimatedArea: 280.0,
        technologyNode: '22nm',
        complexityLevel: 'Critical',
        status: 'Not Started',
        baseHours: 55,
        estimatedHours: 374,
        actualHours: 0,
        aiPredictedHours: 360,
        delayRisk: null,
        priority: 'High',
        createdBy: manager._id,
        dueDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
        ],
      },
      {
        name: 'COMP_StrongArm',
        type: 'Comparator',
        description: 'StrongArm latch comparator for SAR ADC',
        estimatedArea: 35.0,
        technologyNode: '22nm',
        complexityLevel: 'Medium',
        status: 'Completed',
        baseHours: 15,
        estimatedHours: 38.25,
        actualHours: 32,
        aiPredictedHours: 36,
        delayRisk: 'Low',
        priority: 'Medium',
        assignedTo: engineers[2]._id,
        createdBy: manager._id,
        startDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
        completedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
          { status: 'In Progress', changedBy: engineers[2]._id, comment: 'Started' },
          { status: 'DRC', changedBy: engineers[2]._id, comment: 'DRC pass' },
          { status: 'LVS', changedBy: engineers[2]._id, comment: 'LVS pass' },
          { status: 'Review', changedBy: engineers[2]._id, comment: 'Submitted' },
          { status: 'Completed', changedBy: manager._id, comment: 'Approved' },
        ],
        approvals: [{ submittedBy: engineers[2]._id, reviewedBy: manager._id, status: 'approved', comments: 'Clean layout, good job!' }],
      },
      {
        name: 'DAC_R2R_8bit',
        type: 'DAC',
        description: 'R-2R ladder DAC 8-bit for analog output generation',
        estimatedArea: 95.0,
        technologyNode: '65nm',
        complexityLevel: 'Medium',
        status: 'In Progress',
        baseHours: 50,
        estimatedHours: 82.5,
        actualHours: 30,
        aiPredictedHours: 78,
        delayRisk: 'Low',
        priority: 'Medium',
        assignedTo: engineers[2]._id,
        createdBy: manager._id,
        startDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        statusHistory: [
          { status: 'Not Started', changedBy: manager._id, comment: 'Block created' },
          { status: 'In Progress', changedBy: engineers[2]._id, comment: 'Layout started' },
        ],
      },
    ]);

    // Create some notifications
    await Notification.insertMany([
      {
        recipient: engineers[0]._id,
        sender: manager._id,
        type: 'assignment',
        title: 'New Block Assignment',
        message: 'You have been assigned to block "CM_Cascode_HV"',
        blockId: blocks[1]._id,
        read: false,
      },
      {
        recipient: manager._id,
        sender: engineers[1]._id,
        type: 'approval_request',
        title: 'Approval Required',
        message: 'Block "BG_Precision_V2" submitted for approval',
        blockId: blocks[3]._id,
        priority: 'high',
        read: false,
      },
      {
        recipient: manager._id,
        type: 'delay_alert',
        title: '⚠️ High Delay Risk',
        message: 'Block "PLL_Fractional_N" has high delay risk based on current progress',
        blockId: blocks[6]._id,
        priority: 'high',
        read: false,
      },
      {
        recipient: engineers[3]._id,
        sender: manager._id,
        type: 'system',
        title: 'Workload Alert',
        message: 'You currently have 2 active high-complexity blocks. Please update progress.',
        priority: 'medium',
        read: true,
      },
    ]);

    console.log('✅ Database seeded successfully!');
    console.log(`   Created: ${1} manager, ${engineers.length} engineers, ${blocks.length} blocks`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
};

seedDB();
